spring.application.name=email

app.cors.origin=http://localhost:4200
app.domain=local.dev

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=email

storage.endpoint=${StorageEndpoint}
storage.bucket=${StorageBucket}
storage.api.key=${StorageAPIKey}